version: '3.9'

services:
  vue-typescript:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    environment:
      - WATCHPACK_POLLING=true
